## Using Python for Data Science Example

#### Creating a Sample Dataset
###### Note: Using this method creates a list

In [1]:
sample_dataset = [72,37,56,41,22,76,35,11,19,24,77,84,6,32,44,52]
print(sample_dataset)

[72, 37, 56, 41, 22, 76, 35, 11, 19, 24, 77, 84, 6, 32, 44, 52]

#### Importing numpy & using it to transform data into an array

###### Note: This allows us to perform mathematical operations on the items within the "list"

In [2]:
import numpy as np

grades = np.array(sample_dataset)
print(grades)

grades.shape

[72 37 56 41 22 76 35 11 19 24 77 84  6 32 44 52]

(16,)

##### Extracting an item(s) from the array using its index position(s)

In [3]:
# Single item 
#grades[5]

# Multiple items
print(grades[[5,6,7]])

[76 35 11]

#### Finding the mean grade of the dataset

In [4]:
grades.mean()

np.float64(43.0)

#### Finding the lowest grade in the dataset

In [5]:
grades.min()

np.int64(6)

#### Finding the highest grade in the dataset

In [6]:
grades.max()

np.int64(84)

#### Creating a second dataset to represent hours studied

In [7]:
study_hours = [10,4,8,5,3,11,4,2,3,3,9,12,1,4,5,7]
print(study_hours)

[10, 4, 8, 5, 3, 11, 4, 2, 3, 3, 9, 12, 1, 4, 5, 7]

#### Using numpy to create a new array called 'student_data' containing 2 arrays: 'grades' and 'study_hours'

In [8]:
student_data = np.array([study_hours,grades])

#### Syntax for extracting individual items from the arrays within the 'parent' array

In [9]:
#The array index begins at '0'. In this example, this represents 'study_hours' 
student_data[0][1]

np.int64(4)

#### Finding the mean StudyHours and mean Grade/Creating Variables

In [10]:
avg_study = student_data[0].mean()
avg_grade = student_data[1].mean()

# Using formatted string to present averages
print(f'Average study time: {avg_study}\nAverage grade: {avg_grade}')

Average study time: 5.6875
Average grade: 43.0

#### Importing pandas & creating a dataframe

In [11]:
import pandas as pd

df_students = pd.DataFrame({'Name': ['Tom','Jerry','Mickey','Minnie','Johnny','Richard','Arthur','Goliath',
                                     'Broadyway','MacBeth','Elisa','Ashoka','Anakin','Obi-wan','Omega','Wrecker'],
                                     'StudyHours': student_data[0],
                                     'Grade': student_data[1]})

df_students

         Name  StudyHours  Grade
0         Tom          10     72
1       Jerry           4     37
2      Mickey           8     56
3      Minnie           5     41
4      Johnny           3     22
5     Richard          11     76
6      Arthur           4     35
7     Goliath           2     11
8   Broadyway           3     19
9     MacBeth           3     24
10      Elisa           9     77
11     Ashoka          12     84
12     Anakin           1      6
13    Obi-wan           4     32
14      Omega           5     44
15    Wrecker           7     52

#### Extracting an item from the dataframe by using the .loc[ ] method

###### In this example, the parameter essentially represents the row number, starting at '0'

In [12]:
df_students.loc[5]

Name          Richard
StudyHours         11
Grade              76
Name: 5, dtype: object

#### Extracting an item from an individual cell
###### The second parameter 'Grade' represents the name of the column

In [13]:
df_students.loc[5, 'Grade']

np.int64(76)

#### Using a filter expresion to extract data for the row which contains 'Ashoka' in the name column

In [14]:
df_students[df_students.Name=='Ashoka']

      Name  StudyHours  Grade
11  Ashoka          12     84

#### Using a filter expression within the .query( ) method to extract data for row containing 'Ashoka' in name column

In [15]:
df_students.query('Name=="Ashoka"')

      Name  StudyHours  Grade
11  Ashoka          12     84

#### Reading a CSV file into a dataframe
###### In this example, the file is in the same directory folder, so we can use the file name

In [16]:
df_students_2 = pd.read_csv('../data/StudentData.csv')
print(df_students_2)

         Name  StudyHours  Grade
0         Tom        10.0   72.0
1       Jerry         4.0   37.0
2      Mickey         8.0   56.0
3      Minnie         5.0   41.0
4      Johnny         3.0   22.0
5     Richard        11.0   76.0
6      Arthur         4.0   35.0
7     Goliath         2.0   11.0
8   Broadyway         3.0   19.0
9     MacBeth         3.0   24.0
10      Elisa         9.0   77.0
11     Ashoka        12.0   84.0
12     Anakin         1.0    6.0
13    Obi-wan         4.0   32.0
14      Omega         5.0   44.0
15      Gungi         NaN    NaN
16    Xanatos         NaN    NaN

#### Identifying null values
###### The isnull() method returns a DataFrame objectwhere all the values are replaced with a Boolean value True for NULL values, and otherwise False.

In [17]:
df_students_2.isnull()

     Name  StudyHours  Grade
0   False       False  False
1   False       False  False
2   False       False  False
3   False       False  False
4   False       False  False
5   False       False  False
6   False       False  False
7   False       False  False
8   False       False  False
9   False       False  False
10  False       False  False
11  False       False  False
12  False       False  False
13  False       False  False
14  False       False  False
15  False        True   True
16  False        True   True

#### Finding the total number of null vales in each column

In [18]:
df_students_2.isnull().sum()

Name          0
StudyHours    2
Grade         2
dtype: int64

#### Using the dropna( ) function to remove rows that contain NULL values.

###### The dropna() method returns a new DataFrame object unless the inplace parameter is set to True, in that case the dropna() method does the removing in the original DataFrame instead.

In [19]:
df_students_2 = df_students_2.dropna(axis=0) # Rows are axis 0 and columns are axis 1

df_students_2.isnull().sum()

Name          0
StudyHours    0
Grade         0
dtype: int64

#### Finding the mean study_hours and Grade using column names as an index

In [20]:
mean_study = df_students_2["StudyHours"].mean()

mean_grade = df_students_2["Grade"].mean()

print(mean_study, mean_grade)

5.6 42.4

#### Filtering the dataframe to find only the students who studied more than the mean study_hours

In [21]:
df_students_2[df_students_2.StudyHours > mean_study]

       Name  StudyHours  Grade
0       Tom        10.0   72.0
2    Mickey         8.0   56.0
5   Richard        11.0   76.0
10    Elisa         9.0   77.0
11   Ashoka        12.0   84.0

#### Finding the mean grade for students who studied more than the mean study_hours

In [22]:
df_students_2[df_students_2.StudyHours > mean_study].Grade.mean()

np.float64(73.0)

#### Create a new variable to reflect whether a student passed using the pandas series( ) function & adding the series to the dataframe using the concat( ) function
###### Note: this will generate and add a column which contains 'True' if the student passed and 'False' if they did not

In [23]:
passed = pd.Series(df_students_2.Grade >= 60)
df_students_2 = pd.concat([df_students_2, passed.rename('Passed')], axis = 1)

#### Using the groupby( ) operation to separate students into two goups according to whether they passed

In [24]:
df_students_2.groupby(df_students_2.Passed).Name.count()

Passed
False    11
True      4
Name: Name, dtype: int64

#### Finding/Printing the mean grade for each group

In [25]:
print(df_students_2.groupby(df_students_2.Passed).Grade.mean())

Passed
False    29.727273
True     77.250000
Name: Grade, dtype: float64

#### Finding/Printing the mean Grade & StudyHours for each group

In [26]:
print(df_students_2.groupby(df_students_2.Passed)[["Grade", "StudyHours"]].mean())

            Grade  StudyHours
Passed
False   29.727273    3.818182
True    77.250000   10.500000

#### Sorting the dataframe in ascending order according to grade

In [27]:
df_students_2 = df_students_2.sort_values('Grade')
# Alternative Syntax for sorting in decending order
#df_students_2 = df_students_2.sort_values('Grade', ascending=False)